name: My_Git_Hub_Actions

env:
  APPLICATION_NAME: "MyFlask"
  PACKAGE_NAME   : "flask-deploy-ver-${{ github.sha }}"

on:
  push:
    branches:
    - main

jobs:
  my_testing:
      runs-on: ubuntu-latest
      steps:
      - name : Print Hello Message in Testings
        run : echo "Hello World from testings"
